packages:
  - daedalus-dialog-editor
  - daedalus-parser
  - zenkit-node
  - zen-world

onlyBuiltDependencies:
  - electron
  - zenkit-node
  - esbuild
  - tree-sitter
  - tree-sitter-cli
  - unrs-resolver
